apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-static
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-064f4b4783fb37b2e
